// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// sqexp
arma::mat sqexp(arma::mat X, arma::rowvec hyperparams, double scale, double noise);
RcppExport SEXP _gpexperiments_sqexp(SEXP XSEXP, SEXP hyperparamsSEXP, SEXP scaleSEXP, SEXP noiseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type hyperparams(hyperparamsSEXP);
    Rcpp::traits::input_parameter< double >::type scale(scaleSEXP);
    Rcpp::traits::input_parameter< double >::type noise(noiseSEXP);
    rcpp_result_gen = Rcpp::wrap(sqexp(X, hyperparams, scale, noise));
    return rcpp_result_gen;
END_RCPP
}
// c_gpr
List c_gpr(arma::mat K_UL, arma::vec y, arma::mat K_UR, arma::mat K_LR, double noise);
RcppExport SEXP _gpexperiments_c_gpr(SEXP K_ULSEXP, SEXP ySEXP, SEXP K_URSEXP, SEXP K_LRSEXP, SEXP noiseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type K_UL(K_ULSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type K_UR(K_URSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type K_LR(K_LRSEXP);
    Rcpp::traits::input_parameter< double >::type noise(noiseSEXP);
    rcpp_result_gen = Rcpp::wrap(c_gpr(K_UL, y, K_UR, K_LR, noise));
    return rcpp_result_gen;
END_RCPP
}
// nystrom
arma::mat nystrom(arma::mat K, int n_pts);
RcppExport SEXP _gpexperiments_nystrom(SEXP KSEXP, SEXP n_ptsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type n_pts(n_ptsSEXP);
    rcpp_result_gen = Rcpp::wrap(nystrom(K, n_pts));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_gpexperiments_sqexp", (DL_FUNC) &_gpexperiments_sqexp, 4},
    {"_gpexperiments_c_gpr", (DL_FUNC) &_gpexperiments_c_gpr, 5},
    {"_gpexperiments_nystrom", (DL_FUNC) &_gpexperiments_nystrom, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_gpexperiments(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
