# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sqexp <- function(X, hyperparams, scale = 1.0, noise = 1e-6) {
    .Call(`_gpexperiments_sqexp`, X, hyperparams, scale, noise)
}

c_gpr <- function(K_UL, y, K_UR, K_LR, noise) {
    .Call(`_gpexperiments_c_gpr`, K_UL, y, K_UR, K_LR, noise)
}

nystrom <- function(K, n_pts = 10L) {
    .Call(`_gpexperiments_nystrom`, K, n_pts)
}

